bcgov/orgbook-bc-client-vue

- .browserslistrc
- .eslintrc.js
- .gitignore
- README.md
- babel.config.js
- cypress.json
- jest.config.js
- package-lock.json
- package.json
- public/index.html
- public/robots.txt
- src/App.vue
- src/main.ts
- src/registerServiceWorker.ts
- src/router/index.ts
- src/shims-tsx.d.ts
- src/shims-vue.d.ts
- src/store/index.ts
- src/views/About.vue
- src/views/Contact.vue
- src/views/Home.vue
- tests/e2e/.eslintrc.js
- tests/e2e/plugins/index.js
- tests/e2e/specs/test.js
- tests/e2e/support/commands.js
- tests/e2e/support/index.js
- tsconfig.json
> Project scaffolding

- package-lock.json
- package.json
- public/index.html
- src/App.vue
- src/components/contact/ContactForm.vue
- src/components/layout/footer/About.vue
- src/components/layout/footer/Feedback.vue
- src/components/layout/footer/Footer.vue
- src/components/layout/header/Header.vue
- src/components/shared/Loading.vue
- src/components/shared/Notification.vue
- src/config/nav.ts
- src/interfaces/nav-link.ts
- src/main.ts
- src/plugins/vuetify.ts
- src/shims-vuetify.d.ts
- src/store/index.ts
- src/store/modules/app.ts
- src/store/modules/notification.ts
- src/views/Contact.vue
- vue.config.js
This PR adds header and footer components along with responsive application layout, application loading state and a notification module for messages.
> Adds responsive layout

- src/App.vue
- src/components/layout/header/Header.vue
- src/components/layout/header/SubHeader.vue
- src/config/nav.ts
- src/router/index.ts
- src/views/About.vue
- src/views/Contact.vue
- src/views/Home.vue
> Updates layout for views

- package-lock.json
- src/components/contact/ContactForm.vue
- src/services/api/v2/contact.service.ts
- src/services/http.service.ts
- src/store/index.ts
- src/store/modules/contact.ts
- src/store/modules/credential-type.ts
- src/views/Contact.vue
Created contact component.
_Note: the code assumes that a mock api server is running on localhost:3000._
You will need to start `json-server` on the same machine using the command `json-server --watch db.json`. `json-server` can be install with npm.
Here is an example `db.json` file:
```
{
"reasonItems":[
{"text":"My organization's information is incorrect", "value":"incorrect"},
{"text":"I want my organization listed on OrgBook BC", "value":"listed"},
{"text":"I want to become an OrgBook BC issuer", "value":"issuer"},
{"text":"I want more information about APIs", "value":"apiInfo"},
{"text":"other", "value":"other"}
]
}
```
> Feature contact

- src/components/search/SearchBar.vue
- src/components/search/filter/SearchFilterFacetPanel.vue
- src/components/search/filter/SearchFilterFacetPanels.vue
- src/components/search/filter/SearchFilterFacets.vue
- src/components/search/page/SearchTopicPageNavigation.vue
- src/data/search.ts
- src/interfaces/api/v4/search-topic.interface.ts
- src/services/api/v3/search.service.ts
- src/services/api/v4/search.service.ts
- src/store/modules/search.ts
- src/utils/result.ts
- src/utils/search.ts
- src/views/Home.vue
Adds filtering capabilities to search results
TODO:
* Customize labelling of filters
* Clean up mobile dialog actions
* Search trigger on route change rather than page load
> Search filtering

- src/services/api/v3/issuer.service.ts
added simple issuer service to fetch credential issuers
> Issuer service

- src/components/search/SearchBar.vue
> Updates search bar interface to match currnt OrgBook UX

- src/components/contact/ContactForm.vue
- added missing content to contact page on how to add your organization to orgbook
- added contact fields to appear if use clicks `I still need help`
resolves #32
> added missing content to contact page

- src/components/layout/footer/Footer.vue
resolves #33
added scroll to top feature to footer
> added scroll to top feature

- src/components/entity/EntityResult.vue
- src/components/entity/filter/EntityFilterFacetPanels.vue
added dialog box content from issue #31 
Still waiting on text from item 1 of issue
> Feature dialog boxes

- src/components/entity/CredentialItem.vue
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
> fix for highlighted credential attr translation

- src/components/entity/CredentialItem.vue
- src/components/entity/filter/EntityFilterChips.vue
- src/utils/entity.ts
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
added `From` and `To` tags to date filter chips
fixed bug with relationship highlighted attributes
removed console statements
> fix relationship highlighted attributes

- src/components/entity/CredentialItem.vue
- src/components/entity/EntityResult.vue
- src/components/entity/credentialDetail/CredentialDetail.vue
- src/components/entity/filter/EntityFilterFacetPanels.vue
added error checking to source id in urls
minor bug fixes
changed layout and fixed the relationship display list limiter
> Fix redirect on error

- src/components/contact/ContactForm.vue
- src/components/entity/CredentialItem.vue
- src/components/entity/EntityResult.vue
- src/components/entity/credentialDetail/CredentialDetail.vue
- src/components/entity/filter/EntityFilterFacetPanels.vue
- src/interfaces/api/v2/credential-type.interface.ts
- src/interfaces/api/v4/credential.interface.ts
- src/store/modules/entity.ts
- src/utils/entity.ts
updated schema labels in the frontend to match the correct schema_label structure created by the issuer-agency UI
> Feature updated schema labels

- build/docs.js
- build/watch.js
- src/assets/.gitignore
- src/components/contact/ContactForm.vue
- src/components/entity/EntityResult.vue
- src/components/entity/credentialDetail/CredentialDetail.vue
- src/entityDescriptions/bc-company.md
- src/entityDescriptions/cooperative.md
- src/entityDescriptions/extrapro-limited-liability-partnership.md
- src/entityDescriptions/extraprovincial-limited-partnership.md
- src/entityDescriptions/general-partnership.md
- src/entityDescriptions/limited-liability-partnership.md
- src/entityDescriptions/limited-partnership.md
- src/entityDescriptions/society.md
- src/entityDescriptions/sole-proprietorship.md
- src/interfaces/api/v4/credential.interface.ts
- src/interfaces/entity-desc.ts
- src/store/index.ts
- src/store/modules/entity-desc.ts
- src/store/modules/entity.ts
- src/store/modules/search.ts
- src/utils/entity.ts
- added markdown text descriptions for entity types
- created ability to read markdown files from folder and display in entity type dialog box
- fixed credential type labels in search filter
resolves #31
> Feature entity text

- docker/config/Caddyfile
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> Fix /hooks/* routing

- src/components/about/OrgBookData.vue
> Applies localization to credential types on data types page

- src/components/layout/footer/Footer.vue
- src/data/nav.ts
- src/interfaces/nav-link.interface.ts
> Fixes footer links/content

- src/components/search/SearchDescription.vue
> Removes search by license or permit number

- src/i18n/en.json
> Adds Other registration event translation entry 

- src/components/layout/footer/Feedback.vue
> Adds a cancel button to footer feedback 

- src/components/search/SearchBar.vue
- vue.config.js
> Aligns autocomplete results between V1 and V2 front-ends
